#!/bin/bash
sudo touch /var/log/script02.log
sudo chmod 777 /var/log/script02.log
sudo touch /home/file_for_02
sudo chmod 777 /home/file_for_02
sudo touch /home/cron_temp
sudo chmod 777 /home/cron_temp
echo 'sudo apt-get update >> /var/log/script02.log && sudo apt-get upgrade >> /var/log/script02.log' > /home/file_for_02
crontab -l > /home/cron_temp
echo '0 4 * * 1 bash /home/file_for_02' >> /home/cron_temp
crontab /home/cron_temp

# ALSO! If u want crontab sendinding you notices to email crontab file must contain (* * * * * means every minute):
# * * * * * bash /myfolder/myscript | mail -s "Hello!" emailme@mail.com
