#!/bin/bash
sudo touch file
sudo chmod 777 file
sudo touch /home/script04
Sudo chmod 777 /home/script04
m1="$(md5sum '/etc/crontab' | cut -f1 -d' ')"
m2="$(cat 'file')"

if [ "$m1" != "$m2" ] ; then
	md5sum /etc/crontab | cut -f1 -d' ' > file
	echo "not ok" | mail -s "Cronfile was changed" root
fi

sudo touch /home/cron_is_cron
sudo chmod 777 /home/cron_is_cron
crontab -l > /home/cron_is_cron
echo '0 0 * * * bash /home/script04' >> /home/cron_is_cron
crontab /home/cron_is_cron
